### ISSUE TITLE
Negative FPS and feature request

### ISSUE THREAD

**Issue by GalaxyOfWaffles** [notcake/gcompute#14]
http://i.imgur.com/IEl3jql.jpg
This hook only ran once and its saying its adding fps.
Also, please add a right click menu for hooks that allows you to remove the hook instead of typing hook.Remove.

**Comment by notcake** [comment]
The hook profiler in this addon is no longer maintained and liable to break everything when started.

**Comment by SwadicalRag** [comment]
fprofiler integration for  my darkrp server plzz
