### ISSUE TITLE
Admins don't have serverside and no config file?

### ISSUE THREAD

**Issue by SteppuFIN** [notcake/gcompute#5]
I am trying to give my admin serverside access but cant find how to do it and there isnt even config file for doing that...

**Comment by notcake** [comment]
There is no config file for it. Only superadmins can run lua everywhere. Or you can try editing the code yourself to give your admins access. gcompute/execution/local/localexecutionservice.lua, line 26, look for :IsSuperAdmin ()

**Comment by EgrOnWire** [comment]
So, i have edited gcompute/execution/local/localexecutionservice.lua at line 28 adding "or not GCompute.PlayerMonitor:GetUserEntity (authId):IsAdmin ()" to a condition, but admins on my server still can not run lua on server or other players. Is there smthng else i need to edit?
