### ISSUE TITLE
Admins cant run code on other clients and serverside

### ISSUE THREAD

**Issue by EgrOnWire** [notcake/gcompute#6]
As title says, admins on my server cant run code on clients and on the server.
Changing conditon in execution/local/localexecutionservice.lua at line 28 didn't helped me, normal admins cannot run the code. Where and what i need to change to give acess for a non superadmin to run the code on the other clients or the server?

**Comment by notcake** [comment]
You did it wrong.

```Lua
	-- Check permissions
	if authId ~= GLib.GetLocalId () and
	   authId ~= GLib.GetServerId () and
	   authId ~= GLib.GetSystemId () and
	   (not GCompute.PlayerMonitor:GetUserEntity (authId) or not GCompute.PlayerMonitor:GetUserEntity (authId):IsAdmin ()) then
		return false, GCompute.ReturnCode.AccessDenied
	end
```

**Comment by EgrOnWire** [comment]
Thanks, solved the problem to me. I will probably add a ULX support for easy permissions management :smile:

**Comment by EgrOnWire** [comment]
Thanks, solved the problem to me. I will probably add a ULX support for easy permissions management :smile:
